spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1 管理库
                url: jdbc:mysql://172.31.12.251:3306/mis?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: mis_user
                password: hLGik9jcKT#E
            second:  #数据源2 矿场库
                url: jdbc:mysql://172.31.12.251:3306/ctc_customer?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: mis_user
                password: hLGik9jcKT#E
            three:  #数据源3 钱包库
                url: jdbc:mysql://172.31.12.251:3306/ctc_browser?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: mis_user
                password: hLGik9jcKT#E
            four:  #数据源4 浏览器库
                url: jdbc:mysql://172.31.12.251:3306/lw?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: mis_user
                password: hLGik9jcKT#E  
            five:  #数据源5 区块链浏览器
                url: jdbc:mysql://172.31.12.251:3306/ctc_partner?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: mis_user
                password: hLGik9jcKT#E                     
            initial-size: 20
            max-active: 50
            min-idle: 20
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: false
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: false
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: false

    rabbitmq:
      username: admin
      password: CtcQ9F042
      addresses: 172.31.2.234
      port: 5672
      publisher-confirms: true
      virtual-host: /  

wallet:
  socket: 
    host: 172.31.8.185
    port: 50066
    username: ctcrpc
    password: wpMGdbnhJ7YU
    timeout: 15000                     

      
usernameemail: report@credittag.io
password: Re12345
to: yangshifeng@credittag.io,songjianfeng@credittag.io,wangxinguang@credittag.io,hexujun@credittag.io
port: 465
host: smtp.exmail.qq.com